# Generated by Django 4.0.4 on 2022-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'Latop'), ('D', 'Desktop'), ('SP', 'Smartphone')], max_length=2),
        ),
    ]
